export const CATEGORIAS_DETAILS_REQUEST = "CATEGORIAS_DETAILS_REQUEST";
export const CATEGORIAS_DETAILS_SUCCESS = "CATEGORIAS_DETAILS_SUCCESS";
export const CATEGORIAS_DETAILS_FAIL = "CATEGORIAS_DETAILS_FAIL";

export const CATEGORIA_REGISTER_REQUEST = "CATEGORIA_REGISTER_REQUEST";
export const CATEGORIA_REGISTER_SUCCESS = "CATEGORIA_REGISTER_SUCCESS";
export const CATEGORIA_REGISTER_FAIL = "CATEGORIA_REGISTER_FAIL";
export const CATEGORIA_REGISTER_RESET = "CATEGORIA_REGISTER_RESET";

export const CATEGORIA_DELETE_REQUEST = "CATEGORIA_DELETE_REQUEST";
export const CATEGORIA_DELETE_SUCCESS = "CATEGORIA_DELETE_SUCCESS";
export const CATEGORIA_DELETE_FAIL = "CATEGORIA_DELETE_FAIL";

export const CATEGORIA_UPDATE_REQUEST = "CATEGORIA_UPDATE_REQUEST";
export const CATEGORIA_UPDATE_SUCCESS = "CATEGORIA_UPDATE_SUCCESS";
export const CATEGORIA_UPDATE_FAIL = "CATEGORIA_UPDATE_FAIL";
