export const IDIOMAS_DETAILS_REQUEST = "IDIOMAS_DETAILS_REQUEST";
export const IDIOMAS_DETAILS_SUCCESS = "IDIOMAS_DETAILS_SUCCESS";
export const IDIOMAS_DETAILS_FAIL = "IDIOMAS_DETAILS_FAIL";

export const IDIOMAS_USER_DETAILS_REQUEST = "IDIOMAS_USER_DETAILS_REQUEST";
export const IDIOMAS_USER_DETAILS_SUCCESS = "IDIOMAS_USER_DETAILS_SUCCESS";
export const IDIOMAS_USER_DETAILS_FAIL = "IDIOMAS_USER_DETAILS_FAIL";
export const IDIOMAS_USER_DETAILS_RESET = "IDIOMAS_USER_DETAILS_RESET";