export const PALABRAS_DETAILS_REQUEST = "PALABRAS_DETAILS_REQUEST";
export const PALABRAS_DETAILS_SUCCESS = "PALABRAS_DETAILS_SUCCESS";
export const PALABRAS_DETAILS_FAIL = "PALABRAS_DETAILS_FAIL";
export const PALABRAS_DETAILS_RESET = "PALABRAS_DETAILS_RESET";

export const PALABRA_UPDATE_REQUEST = "PALABRA_UPDATE_REQUEST";
export const PALABRA_UPDATE_SUCCESS = "PALABRA_UPDATE_SUCCESS";
export const PALABRA_UPDATE_FAIL = "PALABRA_UPDATE_FAIL";

export const PALABRAS_UPDATE_REPASAR_REQUEST = "PALABRAS_UPDATE_REPASAR_REQUEST";
export const PALABRAS_UPDATE_REPASAR_SUCCESS = "PALABRAS_UPDATE_REPASAR_SUCCESS";
export const PALABRAS_UPDATE_REPASAR_FAIL = "PALABRAS_UPDATE_REPASAR_FAIL";
export const PALABRAS_UPDATE_REPASAR_RESET = "PALABRAS_UPDATE_REPASAR_RESET";

export const PALABRAS_REPASAR_REQUEST = "PALABRAS_REPASAR_REQUEST";
export const PALABRAS_REPASAR_SUCCESS = "PALABRAS_REPASAR_SUCCESS";
export const PALABRAS_REPASAR_FAIL = "PALABRAS_REPASAR_FAIL";
export const PALABRAS_REPASAR_RESET = "PALABRAS_REPASAR_RESET";

export const PALABRA_TRADUCCION_REQUEST = "PALABRAS_TRADUCCION_REQUEST";
export const PALABRA_TRADUCCION_SUCCESS = "PALABRAS_TRADUCCION_SUCCESS";
export const PALABRA_TRADUCCION_FAIL = "PALABRAS_TRADUCCION_FAIL";
export const PALABRA_TRADUCCION_RESET = "PALABRAS_TRADUCCION_RESET";

export const PALABRAS_UPDATE_DIFICULTAD_REQUEST = "PALABRAS_UPDATE_DIFICULTAD_REQUEST";
export const PALABRAS_UPDATE_DIFICULTAD_SUCCESS = "PALABRAS_UPDATE_DIFICULTAD_SUCCESS";
export const PALABRAS_UPDATE_DIFICULTAD_FAIL = "PALABRAS_UPDATE_DIFICULTAD_FAIL";
export const PALABRAS_UPDATE_DIFICULTAD_RESET = "PALABRAS_UPDATE_DIFICULTAD_RESET";

export const PALABRAS_UPDATE_FRASE_REQUEST = "PALABRAS_UPDATE_FRASE_REQUEST";
export const PALABRAS_UPDATE_FRASE_SUCCESS = "PALABRAS_UPDATE_FRASE_SUCCESS";
export const PALABRAS_UPDATE_FRASE_FAIL = "PALABRAS_UPDATE_FRASE_FAIL";
export const PALABRAS_UPDATE_FRASE_RESET = "PALABRAS_UPDATE_FRASE_RESET";