export const TEXTO_REGISTER_REQUEST = "TEXTO_REGISTER_REQUEST";
export const TEXTO_REGISTER_FAIL = "TEXTO_REGISTER_FAIL";
export const TEXTO_REGISTER_SUCCESS = "TEXTO_REGISTER_SUCCESS";
export const TEXTO_REGISTER_RESET = "TEXTO_REGISTER_RESET";

export const TEXTO_UPDATE_REQUEST = "TEXTO_UPDATE_REQUEST";
export const TEXTO_UPDATE_FAIL = "TEXTO_UPDATE_FAIL";
export const TEXTO_UPDATE_SUCCESS = "TEXTO_UPDATE_SUCCESS";
export const TEXTO_UPDATE_RESET = "TEXTO_UPDATE_RESET";

export const TEXTO_DETAILS_REQUEST = "TEXTO_DETAILS_REQUEST";
export const TEXTO_DETAILS_SUCCESS = "TEXTO_DETAILS_SUCCESS";
export const TEXTO_DETAILS_FAIL = "TEXTO_DETAILS_FAIL";
export const TEXTO_DETAILS_RESET = "TEXTO_DETAILS_RESET";

export const TEXTOS_DETAILS_REQUEST = "TEXTOS_DETAILS_REQUEST";
export const TEXTOS_DETAILS_SUCCESS = "TEXTOS_DETAILS_SUCCESS";
export const TEXTOS_DETAILS_FAIL = "TEXTOS_DETAILS_FAIL";

export const TEXTO_DELETE_REQUEST = "TEXTO_DELETE_REQUEST";
export const TEXTO_DELETE_FAIL = "TEXTO_DELETE_FAIL";
export const TEXTO_DELETE_SUCCESS = "TEXTO_DELETE_SUCCESS";
export const TEXTO_DELETE_RESET = "TEXTO_DELETE_RESET";

export const TEXTO_FECHA_ULTIMA_LECTURA_REQUEST = "TEXTO_FECHA_ULTIMA_LECTURA_REQUEST";
export const TEXTO_FECHA_ULTIMA_LECTURA_FAIL = "TEXTO_FECHA_ULTIMA_LECTURA_FAIL";
export const TEXTO_FECHA_ULTIMA_LECTURA_SUCCESS = "TEXTO_FECHA_ULTIMA_LECTURA_SUCCESS";
export const TEXTO_FECHA_ULTIMA_LECTURA_RESET = "TEXTO_FECHA_ULTIMA_LECTURA_RESET";

export const TEXTO_MARCAR_COMO_LEIDO_REQUEST = "TEXTO_MARCAR_COMO_LEIDO_REQUEST";
export const TEXTO_MARCAR_COMO_LEIDO_FAIL = "TEXTO_MARCAR_COMO_LEIDO_FAIL";
export const TEXTO_MARCAR_COMO_LEIDO_SUCCESS = "TEXTO_MARCAR_COMO_LEIDO_SUCCESS";
export const TEXTO_MARCAR_COMO_LEIDO_RESET = "TEXTO_MARCAR_COMO_LEIDO_RESET";

export const TEXTO_CHECK_REQUEST = "TEXTO_CHECK_REQUEST";
export const TEXTO_CHECK_FAIL = "TEXTO_CHECK_FAIL";
export const TEXTO_CHECK_SUCCESS = "TEXTO_CHECK_SUCCESS";
export const TEXTO_CHECK_RESET = "TEXTO_CHECK_RESET";