export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAIL = "USER_INFO_FAIL";
export const USER_INFO_RESET = "USER_INFO_RESET";

export const USER_INFO_ESTADISTICA_REQUEST = "USER_INFO_ESTADISTICA_REQUEST";
export const USER_INFO_ESTADISTICA_SUCCESS = "USER_INFO_ESTADISTICA_SUCCESS";
export const USER_INFO_ESTADISTICA_FAIL = "USER_INFO_ESTADISTICA_FAIL";
export const USER_INFO_ESTADISTICA_RESET = "USER_INFO_ESTADISTICA_RESET";

export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_RESET = "PASSWORD_RESET_RESET";

export const PASSWORD_RESET_CONFIRM_REQUEST = "PASSWORD_RESET_CONFIRM_REQUEST";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_RESET = "PASSWORD_RESET_CONFIRM_RESET";

export const ACTIVATE_ACCOUNT_CONFIRM_REQUEST =
	"ACTIVATE_ACCOUNT_CONFIRM_REQUEST";
export const ACTIVATE_ACCOUNT_CONFIRM_SUCCESS =
	"ACTIVATE_ACCOUNT_CONFIRM_SUCCESS";
export const ACTIVATE_ACCOUNT_CONFIRM_FAIL = "ACTIVATE_ACCOUNT_CONFIRM_FAIL";
export const ACTIVATE_ACCOUNT_CONFIRM_RESET = "ACTIVATE_ACCOUNT_CONFIRM_RESET";
