# Generated by Django 3.2.2 on 2021-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210623_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_nacamiento'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last_login'),
        ),
        migrations.AlterField(
            model_name='account',
            name='metaDiaria',
            field=models.BigIntegerField(default=10, null=True),
        ),
    ]
