# Generated by Django 3.2.2 on 2021-06-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210623_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
