# Generated by Django 3.2.2 on 2021-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_account_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
