# Generated by Django 3.2.2 on 2021-07-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_texto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='fechaUltimaLectura',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='youtubeURL',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
