# Generated by Django 3.2.2 on 2021-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210702_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
