# Generated by Django 3.2.2 on 2021-07-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_texto_youtubeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='youtubeURL',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
