# Generated by Django 3.2.2 on 2021-07-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_categoria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='youtubeURL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
