# Generated by Django 3.2.2 on 2021-07-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_texto_youtubeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='youtubeURL',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
