# Generated by Django 3.2.2 on 2021-07-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_texto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabra',
            name='esFrase',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
