# Generated by Django 3.2.2 on 2021-07-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_palabra_esfrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='cantidadDeRepasosHastaElProximoNivel',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
