# Generated by Django 3.2.2 on 2021-08-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_palabra_cantidadderepasoshastaelproximonivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
