# Generated by Django 3.2.2 on 2021-08-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210803_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sexo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
