# Generated by Django 3.2.2 on 2021-08-31 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_texto_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPalabra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('palabra', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaCreacion', models.DateField(blank=True, editable=False, null=True)),
                ('fechaUltimoRepaso', models.DateField(blank=True, null=True)),
                ('fechaSiguienteRepaso', models.DateField(blank=True, null=True)),
                ('fechaModificacion', models.DateField(blank=True, editable=False, null=True)),
                ('traduccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidadRepasos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cantidadDeRepasosHastaElProximoNivel', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fechaHastaDescenderNivel', models.DateField(blank=True, null=True)),
                ('dificultad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('DiasAAgregarSiCorrecto', models.PositiveIntegerField(blank=True, null=True)),
                ('fechaLeidaPrimeraVez', models.DateField(blank=True, null=True)),
                ('esFrase', models.BooleanField(blank=True, default=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idioma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.idioma')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical palabra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
