# Generated by Django 3.2.2 on 2021-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_historicalpalabra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sexo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
